[build]
builder = "heroku/buildpacks:20"

[[build.buildpacks]]
url = "https://github.com/heroku/heroku-buildpack-google-chrome"

[[build.buildpacks]]
url = "https://github.com/heroku/heroku-buildpack-chromedriver"

[[build.buildpacks]]
url = "heroku/nodejs" 